export const listOfMotoBrands = [
	{ value: 'Aprilia', label: 'Aprilia' },
	{ value: 'Bmw', label: 'Bmw' },
	{ value: 'Can-am', label: 'Can-am' },
	{ value: 'Cf_moto', label: 'Cf moto' },
	{ value: 'Ducati', label: 'Ducati' },
	{ value: 'Genuine_scooter_co.', label: 'Genuine scooter co.' },
	{ value: 'Harley-davidson', label: 'Harley-davidson' },
	{ value: 'Honda', label: 'Honda' },
	{ value: 'Husqvarna', label: 'Husqvarna' },
	{ value: 'Indian_motorcycle_co.', label: 'Indian motorcycle co.' },
	{ value: 'John_deere', label: 'John deere' },
	{ value: 'Kawasaki', label: 'Kawasaki' },
	{ value: 'Ktm', label: 'Ktm' },
	{ value: 'Kymco_usa_inc', label: 'Kymco usa inc' },
	{ value: 'Moto_guzzi', label: 'Moto guzzi' },
	{ value: 'Piaggio', label: 'Piaggio' },
	{ value: 'Polaris', label: 'Polaris' },
	{ value: 'Royal_enfield_motors', label: 'Royal enfield motors' },
	{ value: 'Suzuki', label: 'Suzuki' },
	{ value: 'Triumph_motorcycle', label: 'Triumph motorcycle' },
	{ value: 'Vespa', label: 'Vespa' },
	{ value: 'Victory_motorcycles', label: 'Victory motorcycles' },
	{ value: 'Yamaha', label: 'Yamaha' },
]
