export const listOfCarBrands = [
	{ value: 'Acura', label: 'Acura' },
	{ value: 'Alfa_Romeo', label: 'Alfa Romeo' },
	{ value: 'Aston_Martin', label: 'Aston Martin' },
	{ value: 'Audi', label: 'Audi' },
	{ value: 'Bentley', label: 'Bentley' },
	{ value: 'BMW', label: 'BMW' },
	{ value: 'Bugatti', label: 'Bugatti' },
	{ value: 'Buick', label: 'Buick' },
	{ value: 'Cadillac', label: 'Cadillac' },
	{ value: 'Chevrolet', label: 'Chevrolet' },
	{ value: 'Chrysler', label: 'Chrysler' },
	{ value: 'Dodge', label: 'Dodge' },
	{ value: 'Ferrari', label: 'Ferrari' },
	{ value: 'Fiat', label: 'Fiat' },
	{ value: 'Fisker', label: 'Fisker' },
	{ value: 'Ford', label: 'Ford' },
	{ value: 'Genesis', label: 'Genesis' },
	{ value: 'GMC', label: 'GMC' },
	{ value: 'Honda', label: 'Honda' },
	{ value: 'Hummer', label: 'Hummer' },
	{ value: 'Hyundai', label: 'Hyundai' },
	{ value: 'Infiniti', label: 'Infiniti' },
	{ value: 'Isuzu', label: 'Isuzu' },
	{ value: 'Jaguar', label: 'Jaguar' },
	{ value: 'Jeep', label: 'Jeep' },
	{ value: 'Kia', label: 'Kia' },
	{ value: 'Lamborghini', label: 'Lamborghini' },
	{ value: 'Land_Rover', label: 'Land Rover' },
	{ value: 'Lexus', label: 'Lexus' },
	{ value: 'Lincoln', label: 'Lincoln' },
	{ value: 'Lotus', label: 'Lotus' },
	{ value: 'Lucid', label: 'Lucid' },
	{ value: 'Maserati', label: 'Maserati' },
	{ value: 'Maybach', label: 'Maybach' },
	{ value: 'Mazda', label: 'Mazda' },
	{ value: 'McLaren', label: 'McLaren' },
	{ value: 'Mercedes-Benz', label: 'Mercedes-Benz' },
	{ value: 'Mercury', label: 'Mercury' },
	{ value: 'Mini', label: 'Mini' },
	{ value: 'Mitsubishi', label: 'Mitsubishi' },
	{ value: 'Nissan', label: 'Nissan' },
	{ value: 'Porsche', label: 'Porsche' },
	{ value: 'Ram', label: 'Ram' },
	{ value: 'Rolls-Royce', label: 'Rolls-Royce' },
	{ value: 'Saab', label: 'Saab' },
	{ value: 'Scion', label: 'Scion' },
	{ value: 'Smart', label: 'Smart' },
	{ value: 'Subaru', label: 'Subaru' },
	{ value: 'Suzuki', label: 'Suzuki' },
	{ value: 'Tesla', label: 'Tesla' },
	{ value: 'Toyota', label: 'Toyota' },
	{ value: 'Volkswagen', label: 'Volkswagen' },
	{ value: 'Volvo', label: 'Volvo' },
]
