import { SITE_NAME } from '@/shared/constants/seo.constants'
import { Metadata } from 'next'

export const DefaultMetadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`,
	},
	description: 'Generated by create next app',
}
